//! Parity integration tests for `fleet_kernel::events`.
//!
//! Vectors in `events_vectors.json` were generated by running the live Python
//! `fleet_watch.events._compute_hash` over the same inputs and capturing the
//! hex digests. If Rust and Python ever diverge, these tests catch it.

use fleet_kernel::events::{compute_event_hash, verify_chain, Event, GENESIS_HASH};
use serde::Deserialize;
use std::fs;

// ── JSON vector types ───────────────────────────────────────────────────────

#[derive(Deserialize)]
struct HashVector {
    prev: String,
    ts: String,
    #[serde(rename = "type")]
    event_type: String,
    detail: String,
    hash: String,
}

#[derive(Deserialize)]
struct ChainEvent {
    timestamp: String,
    event_type: String,
    detail: String,
    prev_hash: String,
    hash: String,
}

#[derive(Deserialize)]
struct Vectors {
    hash_vectors: Vec<HashVector>,
    valid_chain: Vec<ChainEvent>,
    tampered_chain: Vec<ChainEvent>,
}

fn load_vectors() -> Vectors {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/events_vectors.json");
    let raw = fs::read_to_string(path).expect("events_vectors.json must exist");
    serde_json::from_str(&raw).expect("events_vectors.json must parse")
}

fn chain_event_to_event(ce: ChainEvent) -> Event {
    Event {
        timestamp: ce.timestamp,
        event_type: ce.event_type,
        detail: ce.detail,
        prev_hash: ce.prev_hash,
        hash: ce.hash,
    }
}

// ── hash parity tests ───────────────────────────────────────────────────────

/// Every tuple in hash_vectors must produce the exact same hex digest as
/// the live Python `_compute_hash`. This is the byte-identical parity gate.
#[test]
fn hash_vectors_match_python() {
    let v = load_vectors();
    assert!(
        !v.hash_vectors.is_empty(),
        "vectors file must have at least one hash vector"
    );
    for (i, vec) in v.hash_vectors.iter().enumerate() {
        let got = compute_event_hash(&vec.prev, &vec.ts, &vec.event_type, &vec.detail);
        assert_eq!(
            got, vec.hash,
            "hash_vector[{i}] mismatch: prev={:?} ts={:?} type={:?} detail={:?}",
            vec.prev, vec.ts, vec.event_type, vec.detail
        );
    }
}

// ── chain verification tests ────────────────────────────────────────────────

/// A properly constructed chain of 3 events must verify as (true, 3).
#[test]
fn valid_chain_verifies() {
    let v = load_vectors();
    let events: Vec<Event> = v
        .valid_chain
        .into_iter()
        .map(chain_event_to_event)
        .collect();
    assert_eq!(events.len(), 3, "expected exactly 3 events in valid chain");
    assert_eq!(
        verify_chain(&events),
        (true, 3),
        "valid chain must return (true, 3)"
    );
}

/// A chain where one event's detail is tampered (hash kept from original)
/// must be detected as invalid and return (false, 0).
#[test]
fn tampered_chain_detected() {
    let v = load_vectors();
    let events: Vec<Event> = v
        .tampered_chain
        .into_iter()
        .map(chain_event_to_event)
        .collect();
    let (valid, _count) = verify_chain(&events);
    assert!(!valid, "tampered chain must not verify as valid");
    assert_eq!(
        verify_chain(&events),
        (false, 0),
        "tampered chain must return (false, 0) matching Python semantics"
    );
}

// ── edge case tests ─────────────────────────────────────────────────────────

#[test]
fn empty_chain_returns_true_zero() {
    assert_eq!(verify_chain(&[]), (true, 0));
}

#[test]
fn single_valid_event_returns_true_one() {
    let h = compute_event_hash(GENESIS_HASH, "2026-06-13T10:00:00+00:00", "REGISTER", "{}");
    let events = vec![Event {
        timestamp: "2026-06-13T10:00:00+00:00".into(),
        event_type: "REGISTER".into(),
        detail: "{}".into(),
        prev_hash: GENESIS_HASH.into(),
        hash: h,
    }];
    assert_eq!(verify_chain(&events), (true, 1));
}

#[test]
fn wrong_prev_hash_on_first_event_fails() {
    // prev_hash must be GENESIS_HASH for first event; anything else = invalid.
    let real_h = compute_event_hash(GENESIS_HASH, "2026-06-13T10:00:00+00:00", "REGISTER", "{}");
    let events = vec![Event {
        timestamp: "2026-06-13T10:00:00+00:00".into(),
        event_type: "REGISTER".into(),
        detail: "{}".into(),
        prev_hash: "not_genesis".into(), // broken linkage
        hash: real_h,
    }];
    assert_eq!(verify_chain(&events), (false, 0));
}
